(function(){
  'use strict';
  var $=function(id){return document.getElementById(id);},core=window.WarmwayCore,levels=window.WarmwayLevels,canvas=$('board'),renderer=new window.WarmwayRenderer(canvas),storageKey='warmway-part1-v1';
  var words={ru:{title:'Тёплый маршрут',build:'ПЕРВАЯ ПОЕЗДКА · 01',district:'КВАРТАЛ 01 / ТИХИЕ ДВОРИКИ',homes:'ОСВЕЩЕНО ДОМОВ',charge:'СВЕТ В ТРАМВАЕ',undo:'Шаг назад',clear:'Сначала',go:'Поехали',footer:'Маленькая поездка. Немного больше света.',route:'Ваш маршрут',stop:'Остановка',station:'Зарядка',planning:'ВЕЧЕР. ВРЕМЯ ЗАЖИГАТЬ ОКНА.',running:'СВЕТ УЖЕ В ПУТИ',paused:'ПОЕЗДКА НА ПАУЗЕ',won:'В ГОРОДЕ СТАЛО ТЕПЛЕЕ',segments:'участков',instruction:'Начните у депо. Проведите путь по улицам или нажимайте на соседние точки.',chargeTip:'Зайдите на станцию с молнией: она пополнит запас до трёх, но сработает только один раз.',ready:'Маршрут замкнут. Нажмите «Поехали» и посмотрите на свою доставку.',continuePath:'Продолжайте от светящейся точки. Завершите путь в депо.',neighbor:'Выберите соседнюю точку, соединённую улицей.',used:'Этот участок уже есть в маршруте. Можно отменить последний шаг.',closed:'Маршрут завершён. Нажмите «Поехали» или измените его.',start:'Начните путь с трамвая у депо.',empty:'Свет закончился. Заедьте на зарядную остановку раньше.',unfinished:'Не все дома получили свет. Включите их в маршрут.',errorTitle:'Попробуем другой путь',edit:'Изменить маршрут',successTitle:'Ещё немного света',successCopy:'Все дома освещены, и трамвай вернулся домой. Следующая улица уже ждёт.',next:'Следующая улица →',lastTitle:'Первые огни зажжены!',lastCopy:'Три учебные поездки завершены. Это первая играбельная часть: дальше появятся новые кварталы и более хитрые маршруты.',replay:'Вернуться к первой улице',stay:'Рассмотреть квартал',pauseTitle:'Тихая остановка',pauseCopy:'Трамвай подождёт. Продолжите поездку, когда будете готовы.',resume:'Продолжить',helpTitle:'Развозим свет',helpKicker:'КАК ИГРАТЬ',helpRules:['Проведите путь от депо по улицам. Можно нажимать на соседние точки.','Каждый дом получает один из трёх зарядов. На третьем уровне появится зарядная остановка.','Каждую улицу можно использовать один раз. Перекрёстки можно посещать повторно.','Замкните путь в депо и нажмите «Поехали». Исправлять маршрут можно сколько угодно.'],understood:'Всё понятно',level:'Уровень',saving:'Браузер не разрешил сохранение. Прогресс останется только до закрытия страницы.',help:'Как играть',pause:'Пауза',board:'Карта улиц. Рисуйте маршрут от депо или нажимайте соседние остановки.'},
  en:{title:'Little Warmway',build:'THE FIRST JOURNEY · 01',district:'DISTRICT 01 / QUIET COURTYARDS',homes:'HOMES LIT',charge:'LIGHT ON BOARD',undo:'Undo',clear:'Start over',go:'Let’s go',footer:'A little journey. A little more light.',route:'Your route',stop:'Stop',station:'Charging',planning:'EVENING. TIME TO LIGHT THE WINDOWS.',running:'LIGHT IS ON ITS WAY',paused:'JOURNEY PAUSED',won:'A WARMER LITTLE TOWN',segments:'segments',instruction:'Start at the depot. Draw along the streets or tap neighboring dots.',chargeTip:'Visit the lightning stop to refill to three charges. It works only once per trip.',ready:'Your route is complete. Press “Let’s go” to watch the delivery.',continuePath:'Continue from the glowing dot. Finish your route at the depot.',neighbor:'Choose a neighboring dot connected by a street.',used:'This street is already in your route. You can undo the last step.',closed:'Your route is complete. Start the tram or edit the route.',start:'Start with the tram at the depot.',empty:'Out of light. Visit the charging stop earlier.',unfinished:'Some homes are still dark. Include them in your route.',errorTitle:'Let’s try another route',edit:'Edit route',successTitle:'A little more light',successCopy:'Every home is glowing and the tram is back. Another street is waiting for you.',next:'Next street →',lastTitle:'The first lights are on!',lastCopy:'Three practice journeys complete. This is the first playable part. More neighborhoods and clever routes will follow.',replay:'Back to the first street',stay:'Enjoy the neighborhood',pauseTitle:'A quiet stop',pauseCopy:'The tram can wait. Continue whenever you are ready.',resume:'Continue',helpTitle:'Deliver a little light',helpKicker:'HOW TO PLAY',helpRules:['Draw a route from the depot along the streets, or tap neighboring dots.','Each home needs one of your three charges. A charging stop appears in level three.','Travel along each street only once. You may revisit junctions.','Finish at the depot and press “Let’s go”. You can edit and retry freely.'],understood:'Got it',level:'Level',saving:'This browser blocked saving. Progress will only last until this page closes.',help:'How to play',pause:'Pause',board:'Street map. Draw from the depot or tap neighboring stops.'}};
  var saved={};try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}')||{};}catch(e){}
  var game={lang:saved.lang==='en'?'en':'ru',index:0,path:[0],state:core.initial(),mode:'planning',tram:null,complete:[],step:1,elapsed:0,modal:null};
  var storageFailed=false,drag=false,lastHit=null,lastTime=0,modalAction=null,secondaryAction=null,toastUntil=0,dialogPreviousMode=null,focusBefore=null;
  if(Array.isArray(saved.complete))game.complete=saved.complete.filter(function(n){return Number.isInteger(n)&&n>=0&&n<levels.length;});
  function tr(key){return words[game.lang][key]||key;}
  function level(){return levels[game.index];}
  function persist(){try{localStorage.setItem(storageKey,JSON.stringify({lang:game.lang,index:game.index,path:game.path,complete:game.complete}));}catch(e){if(!storageFailed){storageFailed=true;toast(tr('saving'));}}}
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');toastUntil=performance.now()+3000;}
  function translate(){document.documentElement.lang=game.lang;document.title=tr('title');document.querySelectorAll('[data-i18n]').forEach(function(el){el.textContent=tr(el.dataset.i18n);});$('language').textContent=game.lang==='ru'?'EN':'RU';$('help').setAttribute('aria-label',tr('help'));$('pause').setAttribute('aria-label',tr('pause'));$('levels').setAttribute('aria-label',game.lang==='ru'?'Уровни':'Levels');canvas.setAttribute('aria-label',tr('board'));renderUI();}
  function renderUI(){var l=level();$('level-title').textContent=game.lang==='ru'?l.ru:l.en;$('level-copy').textContent=game.lang==='ru'?l.copyRu:l.copyEn;$('home-count').innerHTML=game.state.lit.length+' <small>/ '+l.houses.length+'</small>';$('battery').innerHTML=[0,1,2].map(function(n){return '<i class="'+(n<game.state.charge?'on':'')+'"></i>';}).join('');$('battery').setAttribute('aria-label',game.state.charge+' / 3');$('scene-state').textContent=tr(game.mode==='failed'?'planning':game.mode);$('route-count').textContent=(game.path.length-1)+' '+tr('segments');var closed=game.path.length>1&&game.path[game.path.length-1]===l.depot;$('instruction').textContent=tr(closed?'ready':game.path.length>1?'continuePath':game.index===2?'chargeTip':'instruction');var planning=game.mode==='planning';$('go').disabled=!planning||!closed;$('undo').disabled=!planning||game.path.length<2;$('clear').disabled=!planning||game.path.length<2;$('pause').disabled=game.mode==='won'||game.mode==='failed';$('levels').innerHTML='';levels.forEach(function(item,i){var b=document.createElement('button');b.className='level'+(i===game.index?' current':'')+(game.complete.indexOf(i)>=0?' complete':'');b.textContent='0'+(i+1);b.setAttribute('aria-label',tr('level')+' '+(i+1));if(i===game.index)b.setAttribute('aria-current','step');b.disabled=i>0&&game.complete.indexOf(i-1)<0||game.mode==='running'||game.mode==='paused';b.addEventListener('click',function(){load(i);});$('levels').appendChild(b);});}
  function load(index,path){game.index=index;game.path=path&&core.validPath(level(),path)?path.slice():[0];game.state=core.initial();game.mode='planning';game.tram=null;game.elapsed=0;game.step=1;drag=false;lastHit=null;renderUI();persist();}
  function add(id){if(game.mode!=='planning'||game.modal||id===null)return;var last=game.path[game.path.length-1];if(id===last)return;var reason=core.canAppend(level(),game.path,id);if(reason){toast(tr(reason));return;}game.path.push(id);renderUI();persist();}
  function undo(){if(game.mode!=='planning'||game.path.length<2)return;game.path.pop();game.state=core.initial();game.tram=null;renderUI();persist();}
  function showModal(kind,title,copy,primary,action,secondary,secondAction){focusBefore=document.activeElement;game.modal=kind;$('modal-kicker').textContent=kind==='help'?tr('helpKicker'):tr('district');$('modal-title').textContent=title;$('modal-copy').innerHTML=copy;$('modal-primary').textContent=primary;modalAction=action;$('modal-secondary').hidden=!secondary;$('modal-secondary').textContent=secondary||'';secondaryAction=secondAction||null;$('modal-art').textContent=kind==='won'?'✦':kind==='failed'?'↶':kind==='help'?'ϟ':'Ⅱ';$('modal').hidden=false;$('modal-primary').focus();}
  function hideModal(){game.modal=null;$('modal').hidden=true;var previous=focusBefore;focusBefore=null;if(previous&&previous.focus&&!previous.disabled)previous.focus();}
  function edit(){hideModal();game.mode='planning';game.state=core.initial();game.tram=null;renderUI();}
  function result(error){game.mode=error?'failed':'won';if(!error&&game.complete.indexOf(game.index)<0)game.complete.push(game.index);persist();renderUI();if(error)showModal('failed',tr('errorTitle'),'<p>'+tr(error)+'</p>',tr('edit'),edit);else{var last=game.index===levels.length-1;showModal('won',tr(last?'lastTitle':'successTitle'),'<p>'+tr(last?'lastCopy':'successCopy')+'</p>',tr(last?'replay':'next'),function(){hideModal();load(last?0:game.index+1);},tr('stay'),function(){hideModal();game.mode='planning';renderUI();});}}
  function start(){if($('go').disabled||game.modal)return;game.state=core.initial();game.mode='running';game.step=1;game.elapsed=0;var n=level().nodes[0];game.tram={x:n.x,y:n.y,angle:-Math.PI/2};renderUI();}
  function pause(){if(game.modal||game.mode!=='running'&&game.mode!=='planning')return;dialogPreviousMode=game.mode;game.mode='paused';drag=false;renderUI();showModal('pause',tr('pauseTitle'),'<p>'+tr('pauseCopy')+'</p>',tr('resume'),function(){hideModal();game.mode=dialogPreviousMode||'planning';renderUI();});}
  function help(){if(game.modal)return;dialogPreviousMode=game.mode;game.mode='paused';drag=false;renderUI();showModal('help',tr('helpTitle'),tr('helpRules').map(function(s,i){return '<div class="help-rule"><b>'+(i+1)+'</b><span>'+s+'</span></div>';}).join(''),tr('understood'),function(){hideModal();game.mode=dialogPreviousMode||'planning';renderUI();});}
  function localPoint(e){var r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
  function down(e){if(e.button!==undefined&&e.button!==0)return;var p=localPoint(e),id=renderer.hit(level(),p.x,p.y);if(game.mode!=='planning'||game.modal)return;drag=true;lastHit=id;add(id);if(e.pointerId!==undefined&&canvas.setPointerCapture)canvas.setPointerCapture(e.pointerId);if(e.cancelable)e.preventDefault();}
  function move(e){if(!drag)return;var p=localPoint(e),id=renderer.hit(level(),p.x,p.y);if(id!==null&&id!==lastHit){lastHit=id;add(id);}if(e.cancelable)e.preventDefault();}
  function up(){drag=false;lastHit=null;}
  if(window.PointerEvent){canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',up);}else{canvas.addEventListener('mousedown',down);window.addEventListener('mousemove',move);window.addEventListener('mouseup',up);canvas.addEventListener('touchstart',function(e){down(e.touches[0]);e.preventDefault();},{passive:false});canvas.addEventListener('touchmove',function(e){move(e.touches[0]);e.preventDefault();},{passive:false});canvas.addEventListener('touchend',up);canvas.addEventListener('touchcancel',up);}
  canvas.addEventListener('contextmenu',function(e){e.preventDefault();});document.addEventListener('dragstart',function(e){e.preventDefault();});$('undo').onclick=undo;$('clear').onclick=function(){load(game.index);};$('go').onclick=start;$('pause').onclick=pause;$('help').onclick=help;$('language').onclick=function(){game.lang=game.lang==='ru'?'en':'ru';translate();persist();};document.querySelector('.brand').onclick=function(e){e.preventDefault();help();};$('modal-primary').onclick=function(){if(modalAction)modalAction();};$('modal-secondary').onclick=function(){if(secondaryAction)secondaryAction();};
  window.addEventListener('blur',function(){up();if(game.mode==='running')pause();});document.addEventListener('visibilitychange',function(){if(document.hidden){up();if(game.mode==='running')pause();persist();}});window.addEventListener('pagehide',persist);window.addEventListener('resize',function(){renderer.resize();});
  document.addEventListener('keydown',function(e){if(!game.modal)return;if(e.key==='Tab'){var first=$('modal-primary'),last=$('modal-secondary').hidden?first:$('modal-secondary');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  function frame(now){var dt=lastTime?Math.min(now-lastTime,50):0;lastTime=now;if(game.mode==='running'&&!game.modal){var l=level(),a=l.nodes[game.path[game.step-1]],b=l.nodes[game.path[game.step]],length=Math.hypot(b.x-a.x,b.y-a.y),duration=length/145*1000;game.elapsed+=dt;var f=Math.min(game.elapsed/duration,1),ease=f*f*(3-2*f);game.tram={x:a.x+(b.x-a.x)*ease,y:a.y+(b.y-a.y)*ease,angle:Math.atan2(b.y-a.y,b.x-a.x)};if(f>=1){game.state=core.arrive(l,game.state,b.id);game.step++;game.elapsed=0;renderUI();if(game.state.error)result(game.state.error);else if(game.step>=game.path.length)result(game.state.lit.length===l.houses.length?null:'unfinished');}}
    renderer.draw(level(),game,now);if(toastUntil&&now>toastUntil){$('toast').classList.remove('show');toastUntil=0;}window.requestAnimationFrame(frame);}
  var index=Number.isInteger(saved.index)&&saved.index>=0&&saved.index<levels.length?saved.index:0;if(index>0&&game.complete.indexOf(index-1)<0)index=0;load(index,saved.path);translate();renderer.resize();window.requestAnimationFrame(frame);
}());
